### ISSUE TITLE
RuntimeError after training the model

### ISSUE THREAD

**Issue by alexdevmotion** [alexeyev/abae-pytorch#1]
For me, even using `example_run.sh`, it fails in the `_reconstruction_loss` method, after the model finished training.
I tried with other datasets as well and it also fails at the same matrix multiplication.

```
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    y_pred = model(x, negative_samples)
  File "/home/alex/.conda/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/workspace_common/Data-Science/named_entity_recognition/abae_pytorch/model.py", line 109, in forward
    averaged_negative_samples)
  File "/usr/local/workspace_common/Data-Science/named_entity_recognition/abae_pytorch/model.py", line 118, in _reconstruction_loss
    negative_dot_products = torch.matmul(averaged_negative_emb, recovered_emb.unsqueeze(2)).squeeze()
RuntimeError: The size of tensor a (50) must match the size of tensor b (39) at non-singleton dimension 0
```

**Comment by alexeyev** [comment]
Hello, thank you so much! Sorry for the delay.
